# -*- coding: utf-8 -*-
"""
Kaggle Emotion Training Script
==============================
This script is designed to be copy-pasted directly into a Kaggle Notebook (with GPU enabled)
to train the educational emotion classification models:
1. BiLSTM (using Keras/TensorFlow)
2. BERT (fine-tuning Hugging Face Transformers)

Instructions for Kaggle:
-----------------------
1. Create a new notebook on Kaggle (kaggle.com).
2. Set Accelerator to GPU T4 x2 or GPU P100 in the sidebar settings.
3. Upload `student_dataset.csv` generated by the project dataset generator.
4. Copy-paste these cells into individual cells and run them.
"""

# ==================== CELL 1: Install Dependencies ====================
# In a clean Kaggle kernel, install transformers, accelerate, and dataset libraries
!pip install -q transformers[torch] datasets accelerate

# ==================== CELL 2: Imports & Setup ====================
import os
import torch
import numpy as np
import pandas as pd
from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

# Set random seed
np.random.seed(42)
torch.manual_seed(42)

# Verify GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# ==================== CELL 3: Load & Preprocess Data ====================
# Note: Adjust path if you uploaded student_dataset.csv as a Kaggle dataset
csv_path = "/kaggle/input/student-dataset/student_dataset.csv"
if not os.path.exists(csv_path):
    # If dataset is uploaded directly in working directory
    csv_path = "student_dataset.csv"
    
df = pd.read_csv(csv_path)
print(f"Loaded dataset: {len(df)} samples")
print(df.head())

# Encode labels
label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['emotion'])
num_classes = len(label_encoder.classes_)
class_names = list(label_encoder.classes_)
print(f"Classes: {class_names}")

# Split into Train and Validation
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

# Convert to Hugging Face Dataset format
train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

# ==================== CELL 4: Tokenize for BERT ====================
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    return tokenizer(examples['text'], padding="max_length", truncation=True, max_length=128)

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_val = val_dataset.map(tokenize_function, batched=True)

# Prepare dataset formats
tokenized_train = tokenized_train.remove_columns(["text", "__index_level_0__"])
tokenized_val = tokenized_val.remove_columns(["text", "__index_level_0__"])
tokenized_train.set_format("torch")
tokenized_val.set_format("torch")

# ==================== CELL 5: Fine-tune BERT Sequence Classifier ====================
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_classes)
model.to(device)

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    report_to="none" # Disable logging to external trackers
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = np.mean(predictions == labels)
    return {"accuracy": float(acc)}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    compute_metrics=compute_metrics,
)

# Run fine-tuning
print("Starting BERT training on GPU...")
trainer.train()

# Save final BERT model
model.save_pretrained("./fine_tuned_bert")
tokenizer.save_pretrained("./fine_tuned_bert")
print("Saved BERT model to ./fine_tuned_bert directory.")

# ==================== CELL 6: Optional TensorFlow BiLSTM Model ====================
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer as KerasTokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout

# Prepare tokenization for BiLSTM
vocab_size = 5000
max_len = 128
k_tokenizer = KerasTokenizer(num_words=vocab_size, oov_token="<OOV>")
k_tokenizer.fit_on_texts(df['text'])

sequences_train = k_tokenizer.texts_to_sequences(train_df['text'])
padded_train = pad_sequences(sequences_train, maxlen=max_len, padding='post', truncating='post')

sequences_val = k_tokenizer.texts_to_sequences(val_df['text'])
padded_val = pad_sequences(sequences_val, maxlen=max_len, padding='post', truncating='post')

# Define model
tf_model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=128, input_length=max_len),
    Bidirectional(LSTM(64, return_sequences=False)),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dropout(0.4),
    Dense(num_classes, activation='softmax')
])

tf_model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Train on Kaggle
print("Starting BiLSTM training...")
tf_model.fit(
    padded_train, train_df['label'].values,
    epochs=15,
    batch_size=32,
    validation_data=(padded_val, val_df['label'].values)
)

tf_model.save("./bilstm_model.keras")
print("Saved BiLSTM model to ./bilstm_model.keras")
